### ISSUE TITLE
Create environment files for R and Python

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ocean_sciences_bio_workshop_2021#3]
Create environment files which can be picked up by Binder to spin up a Python or R environment, if folks have trouble locally.
- [ ] Python
- [ ] R
- [ ] Do we want a combined environment like the [IOOS conda env](https://github.com/ioos/ioos_code_lab/blob/main/.binder/environment-python_and_r.yml)?

**Comment by 7yl4r** [comment]
I would say that the only downside to having a combined environment would be loading time. I quickly added enough packages to slow my binder startup down to multiple minutes.

That being said: the ability to jump between R & python is pretty awesome.

**Comment by MathewBiddle** [comment]
For reference: https://github.com/alan-turing-institute/the-turing-way/blob/main/workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder-python.md

**Comment by MathewBiddle** [comment]
@albenson-usgs what default R packages should we have in the R environment?

**Comment by albenson-usgs** [comment]
Probably: tidyverse, Hmisc, worrms, lubridate, readr, robis

**Comment by MathewBiddle** [comment]
https://mybinder.org/v2/gh/ioos/ocean_sciences_bio_workshop_2021/e77c33a5e0837a4c8de8b3bc31ac8522b554aab0 
should work

![image](https://user-images.githubusercontent.com/8480023/146210437-9e37fe3e-d4bc-43d5-bb9f-aa93d32f8c81.png)

Can't get Rstudio to work though...

**Comment by MathewBiddle** [comment]
Think RStudio will work if we don't specify the r-base version. See this [environment](https://github.com/ioos/ocean_sciences_bio_workshop_2021/blob/ba724bcba505d0fad76ad0682ad2634a9794329d/.binder/environment.yml), which deploys [this RStudio in mybinder](https://mybinder.org/v2/gh/ioos/ocean_sciences_bio_workshop_2021/ba724bcba505d0fad76ad0682ad2634a9794329d?urlpath=rstudio).

just working on testing if adding all the needed packages still works with the RStudio through mybinder now.

**Comment by MathewBiddle** [comment]
yay! Works now:
![image](https://user-images.githubusercontent.com/8480023/146235951-9af138de-7ffa-40a8-8ce5-ce74fdb25292.png)
